# Generated by Django 5.2.7 on 2025-10-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_venda_produto_remove_venda_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(default=123456, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
