# Generated by Django 5.2.7 on 2025-10-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_venda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('DEBITO', 'Débito'), ('DINHEIRO', 'Dinheiro'), ('CREDITO', 'Crédito')], default='DINHEIRO', max_length=8, verbose_name='Forma de Pagamento'),
        ),
    ]
